# Linear Algebra

In [2]:
import numpy as np


In [3]:
x=np.array([1, 2, 3, 4]) #declaring a vector
print(x)
print(x.shape)
print(len(x))

[1 2 3 4]
(4,)
4


In [4]:
A = np.array([[1, 2], [3, 4], [5, 6]])  #declaring a Matrx 3x2
print(A)
print(A.shape)
print(len(A))

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
3


In [5]:
print(np.eye(3)) #Identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [18]:
xi = np.eye(x.shape[0]).dot(x)
xi

array([[1.],
       [2.],
       [3.]])

In [95]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

Transpose
----------------------

In [96]:
A_t = A.T #Transpose of Vector 
A_t

array([[1, 3, 5],
       [2, 4, 6]])

In [97]:
print(A.shape)
print(len(A))

(3, 2)
3


In [98]:
print(A_t.shape)
print(len(A_t))

(2, 3)
2


Addition
---------------------

In [99]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[2, 2], [3, 3], [5, 5]])

In [100]:
c=A+B    #Addiditon of 2 vectors
c

array([[ 3,  4],
       [ 6,  7],
       [10, 11]])

In [101]:
c

array([[ 3,  4],
       [ 6,  7],
       [10, 11]])

In [102]:
A = np.array([[1, 2], [3, 4], [5, 6]])   #addition with scalar
c=5+A
c

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [103]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B=np.array([[2],[4],[5]])
print(A.shape)
print(B.shape)
print(len(A))
print(len(B))

(3, 2)
(3, 1)
3
3


In [104]:
c=A+B   #add Two matrix with differrnt dimension  
c

array([[ 3,  4],
       [ 7,  8],
       [10, 11]])

Multiplication
-----------------------

In [105]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
print(A.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [106]:
B = np.array([[2], [4]])
print(B)
print(B.shape)

[[2]
 [4]]
(2, 1)


In [107]:
C = np.dot(A, B) #dot product or multiplication of matrx [Cij=Aij x Bij] if Aj=Bi column of matrix A equal to row of matrx B
print(C)
print(c.shape)
print(len(A))

[[10]
 [22]
 [34]]
(3, 2)
3


In [108]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [109]:
B = np.array([[2, 7], [1, 2], [3, 6]])
B

array([[2, 7],
       [1, 2],
       [3, 6]])

In [110]:
c=A.dot(B)
c

array([[ 13,  29],
       [ 31,  74],
       [ 49, 119],
       [ 67, 164]])

# Matrices mutliplication is distributive       A(B+C)=AB+AC

In [111]:
A = np.array([[2, 3], [1, 4], [7, 6]])
B = np.array([[5], [2]])
C = np.array([[4], [3]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [112]:
B

array([[5],
       [2]])

In [113]:
C

array([[4],
       [3]])

In [114]:
D=A.dot(B+C)
D

array([[33],
       [29],
       [93]])

In [115]:
E=A.dot(B)+A.dot(C)
E

array([[33],
       [29],
       [93]])

# Matrices mutliplication is associative A(BC)=(AB)C

In [116]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [117]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

In [118]:
C

array([[4],
       [3]])

In [119]:
D = A.dot(np.dot(B, C))
D

array([[100],
       [ 85],
       [287]])

In [120]:
E=(np.dot(A,B)).dot(C)
E

array([[100],
       [ 85],
       [287]])

# Matrix multiplication is not commutative AB≠BA

In [121]:
A = np.array([[2, 3], [6, 5]])
A

array([[2, 3],
       [6, 5]])

In [122]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

In [123]:
AB = A.dot(B)
AB

array([[16, 12],
       [40, 28]])

In [124]:
BA= np.dot(B,A)
BA

array([[28, 30],
       [16, 16]])

# vector multiplication is commutative xTy=yTx

In [125]:
x = np.array([[2], [6]])
x

array([[2],
       [6]])

In [126]:
y = np.array([[5], [2]])
y

array([[5],
       [2]])

In [127]:
xTy = x.T.dot(y)
xTy

array([[22]])

In [128]:
yTx=y.T.dot(x)
yTx

array([[22]])

# Simplification of the matrix product (xy)T=yTxT

In [133]:
x=np.array([[2, 3], [1, 4], [7, 6]])
y=np.array([[5, 3], [2, 2]])

In [134]:
c=x.dot(y).T

In [135]:
d=y.T.dot(x.T)

In [136]:
print(c)
print(d)

[[16 13 47]
 [12 11 33]]
[[16 13 47]
 [12 11 33]]


# Inverse Matrices

In [51]:
A = np.array([[1,2,3], [0,1, 4], [5,6,0]])
A

array([[1, 2, 3],
       [0, 1, 4],
       [5, 6, 0]])

In [54]:
Ai = np.linalg.inv(A)
Ai

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [55]:
In=Ai.dot(A) #A−1.A=In
In

array([[ 1.00000000e+00, -8.88178420e-15, -1.42108547e-14],
       [ 1.77635684e-15,  1.00000000e+00,  0.00000000e+00],
       [-4.44089210e-16, -8.88178420e-16,  1.00000000e+00]])