# Linear Algebra

In [56]:
import numpy as np


In [57]:
x=np.array([1, 2, 3, 4]) #declaring a vector
print(x)
print(x.shape)
print(len(x))

[1 2 3 4]
(4,)
4


In [58]:
A = np.array([[1, 2], [3, 4], [5, 6]])  #declaring a Matrx 3x2
print(A)
print(A.shape)
print(len(A))

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
3


In [59]:
print(np.eye(3)) #Identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [60]:
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [61]:
xi = np.eye(x.shape[0]).dot(x)
xi

array([[1.],
       [2.],
       [3.]])

In [62]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

Transpose
----------------------

In [63]:
A_t = A.T #Transpose of Vector 
A_t

array([[1, 3, 5],
       [2, 4, 6]])

In [64]:
print(A.shape)
print(len(A))

(3, 2)
3


In [65]:
print(A_t.shape)
print(len(A_t))

(2, 3)
2


Addition
---------------------

In [66]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[2, 2], [3, 3], [5, 5]])

In [67]:
c=A+B    #Addiditon of 2 vectors
c

array([[ 3,  4],
       [ 6,  7],
       [10, 11]])

In [68]:
c

array([[ 3,  4],
       [ 6,  7],
       [10, 11]])

In [69]:
A = np.array([[1, 2], [3, 4], [5, 6]])   #addition with scalar
c=5+A
c

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [70]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B=np.array([[2],[4],[5]])
print(A.shape)
print(B.shape)
print(len(A))
print(len(B))

(3, 2)
(3, 1)
3
3


In [71]:
c=A+B   #add Two matrix with differrnt dimension  
c

array([[ 3,  4],
       [ 7,  8],
       [10, 11]])

Multiplication
-----------------------

In [72]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
print(A.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [73]:
B = np.array([[2], [4]])
print(B)
print(B.shape)

[[2]
 [4]]
(2, 1)


In [74]:
C = np.dot(A, B) #dot product or multiplication of matrx [Cij=Aij x Bij] if Aj=Bi column of matrix A equal to row of matrx B
print(C)
print(c.shape)
print(len(A))

[[10]
 [22]
 [34]]
(3, 2)
3


In [75]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [76]:
B = np.array([[2, 7], [1, 2], [3, 6]])
B

array([[2, 7],
       [1, 2],
       [3, 6]])

In [77]:
c=A.dot(B)
c

array([[ 13,  29],
       [ 31,  74],
       [ 49, 119],
       [ 67, 164]])

# Matrices mutliplication is distributive       A(B+C)=AB+AC

In [79]:
A = np.array([[2, 3], [1, 4], [7, 6]])
B = np.array([[5], [2]])
C = np.array([[4], [3]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [80]:
B

array([[5],
       [2]])

In [81]:
C

array([[4],
       [3]])

In [82]:
D=A.dot(B+C)
D

array([[33],
       [29],
       [93]])

In [83]:
E=A.dot(B)+A.dot(C)
E

array([[33],
       [29],
       [93]])

# Matrices mutliplication is associative A(BC)=(AB)C

In [84]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [85]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

In [86]:
C

array([[4],
       [3]])

In [87]:
D = A.dot(np.dot(B, C))
D

array([[100],
       [ 85],
       [287]])

In [88]:
E=(np.dot(A,B)).dot(C)
E

array([[100],
       [ 85],
       [287]])

# Matrix multiplication is not commutative AB≠BA

In [89]:
A = np.array([[2, 3], [6, 5]])
A

array([[2, 3],
       [6, 5]])

In [90]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

In [91]:
AB = A.dot(B)
AB

array([[16, 12],
       [40, 28]])

In [92]:
BA= np.dot(B,A)
BA

array([[28, 30],
       [16, 16]])

# vector multiplication is commutative xTy=yTx

In [93]:
x = np.array([[2], [6]])
x

array([[2],
       [6]])

In [94]:
y = np.array([[5], [2]])
y

array([[5],
       [2]])

In [95]:
xTy = x.T.dot(y)
xTy

array([[22]])

In [96]:
yTx=y.T.dot(x)
yTx

array([[22]])

# Simplification of the matrix product (xy)T=yTxT

In [97]:
x=np.array([[2, 3], [1, 4], [7, 6]])
y=np.array([[5, 3], [2, 2]])

In [98]:
c=x.dot(y).T

In [99]:
d=y.T.dot(x.T)

In [100]:
print(c)
print(d)

[[16 13 47]
 [12 11 33]]
[[16 13 47]
 [12 11 33]]


# Inverse Matrices

In [101]:
A = np.array([[1,2,3], [0,1, 4], [5,6,0]])
A

array([[1, 2, 3],
       [0, 1, 4],
       [5, 6, 0]])

In [102]:
Ai = np.linalg.inv(A)
Ai

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [103]:
In=Ai.dot(A) #A−1.A=In
In

array([[ 1.00000000e+00, -8.88178420e-15, -1.42108547e-14],
       [ 1.77635684e-15,  1.00000000e+00,  0.00000000e+00],
       [-4.44089210e-16, -8.88178420e-16,  1.00000000e+00]])