# Linear Algebra

In [4]:
import numpy as np


In [35]:
x=np.array([1, 2, 3, 4]) #declaring a vector
print(x)
print(x.shape)
print(len(x))

[1 2 3 4]
(4,)
4


In [9]:
A = np.array([[1, 2], [3, 4], [5, 6]])  #declaring a Matrx 3x2

In [10]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
A.shape

(3, 2)

In [12]:
len(A)

3

In [50]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

Transpose
----------------------

In [ ]:
A_t = A.T #Transpose of Vector 
A_t

In [15]:
print(A.shape)
print(len(A))

(3, 2)
3


In [16]:
print(A_t.shape)
print(len(A_t))

(2, 3)
2


Addition
---------------------

In [17]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[2, 2], [3, 3], [5, 5]])

In [18]:
c=A+B    #Addiditon of 2 vectors
c

array([[ 3,  4],
       [ 6,  7],
       [10, 11]])

In [19]:
c

array([[ 3,  4],
       [ 6,  7],
       [10, 11]])

In [20]:
A = np.array([[1, 2], [3, 4], [5, 6]])   #addition with scalar
c=5+A
c

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B=np.array([[2],[4],[5]])
print(A.shape)
print(B.shape)
print(len(A))
print(len(B))

(3, 2)
(3, 1)
3
3


In [22]:
c=A+B   #add Two matrix with differrnt dimension  
c

array([[ 3,  4],
       [ 7,  8],
       [10, 11]])

Multiplication
-----------------------

In [41]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
print(A.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [42]:
B = np.array([[2], [4]])
print(B)
print(B.shape)

[[2]
 [4]]
(2, 1)


In [43]:
C = np.dot(A, B) #dot product or multiplication of matrx [Cij=Aij x Bij] if Aj=Bi column of matrix A equal to row of matrx B
print(C)
print(c.shape)
print(len(A))

[[10]
 [22]
 [34]]
(4, 2)
3


In [44]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
B = np.array([[2, 7], [1, 2], [3, 6]])
B

array([[2, 7],
       [1, 2],
       [3, 6]])

In [49]:
c=A.dot(B)
c

array([[ 13,  29],
       [ 31,  74],
       [ 49, 119],
       [ 67, 164]])